name: Task Notifications
on:
  workflow_dispatch:

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore state cache
        uses: actions/cache/restore@v4
        with:
          path: state.json
          key: state-${{ github.run_id }}
          restore-keys: |
            state-

      - name: Clone private vault
        env:
          PAT: ${{ secrets.PRIVATE_REPO_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          OBSIDIAN_VAULT_REPO_NAME: ${{ secrets.OBSIDIAN_VAULT_REPO_NAME }}
        run: |
          git clone --depth 1 https://x-access-token:${PAT}@github.com/${USER_NAME}/${OBSIDIAN_VAULT_REPO_NAME}.git vault

      - name: Run notification script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          VAULT_PATH: vault
          STATE_FILE_PATH: ${{ github.workspace }}/state.json
          TZ: 'Europe/Saratov'
        run: dotnet run --project ObsidianTaskNotifier/ObsidianTaskNotifier.csproj

      - name: Save state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: state.json
          key: state-${{ github.run_id }}