name: Task Notifications

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код скрипта из публичного репозитория
      - name: Checkout public repo
        uses: actions/checkout@v4


      - name: Check timezone
        run: date +"%Z %z"
      
      # 2. Устанавливаем .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # 3. Клонируем приватный vault
      - name: Clone private vault
        env:
          PAT: ${{ secrets.PRIVATE_REPO_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          OBSIDIAN_VAULT_REPO_NAME: ${{ secrets.OBSIDIAN_VAULT_REPO_NAME }}
        run: |
          git clone --depth 1 https://x-access-token:${PAT}@github.com/${USER_NAME}/${OBSIDIAN_VAULT_REPO_NAME}.git vault

      # 4. Запускаем скрипт
      - name: Run notification script
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          VAULT_PATH: vault
          TZ: 'Europe/Saratov'   # или Europe/Moscow если время московское
        run: dotnet run --project ObsidianTaskNotifier/ObsidianTaskNotifier.csproj
      
      # 5. Коммитим изменения state.json обратно в публичный репозиторий
      - name: Commit state changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add state.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update notification state"
          git push origin HEAD:master