name: workflow.yml

on:
  schedule:
    # Шаблон cron для запуска каждые 5 минут
    - cron: "*/5 * * * *"
  
  # Позволяет запускать этот workflow вручную кнопкой в интерфейсе GitHub (вкладка Actions)
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Execute Your Task
        run: |
          echo "Этот скрипт запускается каждые 5 минут!"
          # Добавьте сюда ваши команды (например, запуск скрипта)
          # python script.py или npm run start